window:
  opacity: 0.92
  dimensions:
    columns: 100
    lines: 30

font:
  size: 12.0

draw_bold_text_with_bright_colors: false

cursor:
  style:
    blinking: On

dynamic_title: true

key_bindings:
  - { key: V,              mods: Control,       action: Paste            }
  - { key: Q,              mods: Control,       action: Quit             }
  - { key: N,              mods: Control,       action: SpawnNewInstance }
  - { key: Return,         mods: Alt,           action: ToggleFullscreen }
  - { key: Equals,         mods: Control,       action: IncreaseFontSize }
  - { key: Plus,           mods: Control,       action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,       action: IncreaseFontSize }
  - { key: Minus,          mods: Control,       action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,       action: DecreaseFontSize }
  - { key: Key0,           mods: Control,       action: ResetFontSize    }

import:
  - ~/.config/alacritty/white_on_black.yml
